# Relatório de Análise III
## Imóveis Residenciais

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('aluguel.csv', sep = ';')

In [3]:
dados.head(10)

                      Tipo           Bairro  ...  Condominio    IPTU
0                Quitinete       Copacabana  ...       500.0    60.0
1                     Casa  Jardim Botânico  ...         NaN     NaN
2  Conjunto Comercial/Sala  Barra da Tijuca  ...      4020.0  1111.0
3              Apartamento           Centro  ...       390.0    20.0
4              Apartamento     Higienópolis  ...       230.0     NaN
5              Apartamento     Vista Alegre  ...         NaN     NaN
6              Apartamento         Cachambi  ...       301.0    17.0
7       Casa de Condomínio  Barra da Tijuca  ...         NaN     NaN
8       Casa de Condomínio            Ramos  ...         NaN     NaN
9  Conjunto Comercial/Sala           Centro  ...     19193.0  3030.0

[10 rows x 9 columns]

In [4]:
list(dados['Tipo'].drop_duplicates())

['Quitinete',
 'Casa',
 'Conjunto Comercial/Sala',
 'Apartamento',
 'Casa de Condomínio',
 'Prédio Inteiro',
 'Flat',
 'Loja/Salão',
 'Galpão/Depósito/Armazém',
 'Casa Comercial',
 'Casa de Vila',
 'Terreno Padrão',
 'Box/Garagem',
 'Loft',
 'Loja Shopping/ Ct Comercial',
 'Chácara',
 'Loteamento/Condomínio',
 'Sítio',
 'Pousada/Chalé',
 'Studio',
 'Hotel',
 'Indústria']

In [5]:
residencial = ['Quitinete',
 'Casa',
 'Apartamento',
 'Casa de Condomínio',
 'Casa de Vila',]

In [6]:
filtro = dados['Tipo'].isin(residencial)

In [7]:
dados_residencial = dados[filtro]

In [8]:
dados_residencial

              Tipo                Bairro  Quartos  ...   Valor  Condominio  IPTU
0        Quitinete            Copacabana        1  ...  1700.0       500.0  60.0
1             Casa       Jardim Botânico        2  ...  7000.0         NaN   NaN
3      Apartamento                Centro        1  ...   800.0       390.0  20.0
4      Apartamento          Higienópolis        1  ...   800.0       230.0   NaN
5      Apartamento          Vista Alegre        3  ...  1200.0         NaN   NaN
...            ...                   ...      ...  ...     ...         ...   ...
32953  Apartamento                 Méier        2  ...   900.0       490.0  48.0
32955    Quitinete                Centro        0  ...   800.0       350.0  25.0
32956  Apartamento           Jacarepaguá        3  ...  1800.0       800.0  40.0
32957  Apartamento  São Francisco Xavier        2  ...  1400.0       509.0  37.0
32958  Apartamento                Leblon        2  ...  3000.0       760.0   NaN

[22580 rows x 9 columns]

In [9]:
dados_residencial['Tipo'].drop_duplicates()

0               Quitinete
1                    Casa
3             Apartamento
7      Casa de Condomínio
117          Casa de Vila
Name: Tipo, dtype: object

In [10]:
dados_residencial.shape[0]

22580

In [11]:
dados_residencial.index = range(dados_residencial.shape[0])

In [12]:
dados_residencial

              Tipo                Bairro  Quartos  ...   Valor  Condominio  IPTU
0        Quitinete            Copacabana        1  ...  1700.0       500.0  60.0
1             Casa       Jardim Botânico        2  ...  7000.0         NaN   NaN
2      Apartamento                Centro        1  ...   800.0       390.0  20.0
3      Apartamento          Higienópolis        1  ...   800.0       230.0   NaN
4      Apartamento          Vista Alegre        3  ...  1200.0         NaN   NaN
...            ...                   ...      ...  ...     ...         ...   ...
22575  Apartamento                 Méier        2  ...   900.0       490.0  48.0
22576    Quitinete                Centro        0  ...   800.0       350.0  25.0
22577  Apartamento           Jacarepaguá        3  ...  1800.0       800.0  40.0
22578  Apartamento  São Francisco Xavier        2  ...  1400.0       509.0  37.0
22579  Apartamento                Leblon        2  ...  3000.0       760.0   NaN

[22580 rows x 9 columns]

## Exportando a base de dados

In [13]:
dados_residencial.to_csv('residencial.csv', sep = ';', index = False)

In [14]:
dados2 = pd.read_csv('residencial.csv', sep = ';')